#!/usr/bin/env python3
"""BlackRoad Mastodon Bot — posts world artifacts to Mastodon/Fediverse"""

import os, json, httpx, time
from datetime import datetime, timezone
from pathlib import Path

MASTODON_URL = os.environ.get("MASTODON_URL", "https://mastodon.social")
ACCESS_TOKEN = os.environ.get("MASTODON_ACCESS_TOKEN", "")
WORLDS_API   = "https://worlds.blackroad.io/"
POSTED_FILE  = Path.home() / ".blackroad" / "mastodon_posted.json"

def load_posted():
    if POSTED_FILE.exists():
        return set(json.loads(POSTED_FILE.read_text()))
    return set()

def save_posted(posted):
    POSTED_FILE.parent.mkdir(parents=True, exist_ok=True)
    POSTED_FILE.write_text(json.dumps(list(posted)))

def fetch_latest_worlds(limit=5):
    try:
        r = httpx.get(WORLDS_API, timeout=10)
        r.raise_for_status()
        return r.json().get("worlds", [])[:limit]
    except Exception as e:
        print(f"[fetch] error: {e}")
        return []

def post_toot(content: str) -> bool:
    if not ACCESS_TOKEN:
        print(f"[DRY RUN] Would post: {content[:80]}...")
        return True
    try:
        r = httpx.post(
            f"{MASTODON_URL}/api/v1/statuses",
            headers={"Authorization": f"Bearer {ACCESS_TOKEN}"},
            json={"status": content, "visibility": "public"},
            timeout=15,
        )
        r.raise_for_status()
        print(f"[posted] {r.json().get(\"id\")}")
        return True
    except Exception as e:
        print(f"[post] error: {e}")
        return False

def format_world(w: dict) -> str:
    icons = {"world": "🌍", "lore": "📖", "code": "💻"}
    node_icons = {"aria64": "🔴", "alice": "🔵"}
    icon = icons.get(w["type"], "⚪")
    ni = node_icons.get(w["node"], "⚫")
    ts = w["timestamp"][:16].replace("T", " ")
    return (
        f"{icon} New BlackRoad World Artifact\n\n"
        f"**{w[\"title\"]}** ({w[\"type\"]})\n"
        f"Generated by {ni} {w[\"node\"]} at {ts} UTC\n\n"
        f"🔗 {w[\"link\"]}\n\n"
        f"#BlackRoadOS #AI #GenerativeAI #WorldBuilding"
    )

def run():
    posted = load_posted()
    worlds = fetch_latest_worlds(10)
    new_posts = [w for w in worlds if w["id"] not in posted]

    if not new_posts:
        print("[bot] no new worlds to post")
        return

    # Post 1 at a time to avoid spam
    world = new_posts[0]
    content = format_world(world)
    if post_toot(content):
        posted.add(world["id"])
        save_posted(posted)
        print(f"[bot] posted world: {world[\"id\"]}")

if __name__ == "__main__":
    run()

