name = "index-blackroad"
main = "src/worker.js"
compatibility_date = "2024-12-01"
workers_dev = true

routes = [
  { pattern = "index.blackroad.io/*", zone_name = "blackroad.io" }
]

[triggers]
crons = ["*/30 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "index-blackroad"
database_id = "5599c9ac-5bb9-430a-9743-c32d873b9e78"

[vars]
GITEA_URL = "http://192.168.4.100:3100"
GITEA_PUBLIC_URL = "https://git.blackroad.io"
GITHUB_USER = "blackboxprogramming"
