name = "images-blackroad"
main = "src/worker.js"
compatibility_date = "2024-12-01"
workers_dev = true

routes = [
  { pattern = "images.blackroad.io/*", zone_name = "blackroad.io" }
]

[[d1_databases]]
binding = "DB"
database_name = "images-blackroad"
database_id = "98ddb91d-4705-4531-969e-a0b3fb8a4c57"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "blackroad-images"

[vars]
MAX_UPLOAD_SIZE = "10485760"
