#!/bin/bash
# Generate markdown KPI report (for GitHub README auto-update)

source "$(dirname "$0")/../lib/common.sh"

DAILY=$(today_file)
OUT="$KPI_ROOT/LATEST.md"

if [ ! -f "$DAILY" ]; then
  err "No daily data for $TODAY"
  exit 1
fi

python3 -c "
import json

with open('$DAILY') as f:
    data = json.load(f)

s = data['summary']

md = f'''# BlackRoad OS KPIs — {data['date']}

> Auto-generated daily at {data['collected_at']}

## Code Activity
| Metric | Value |
|--------|-------|
| Commits today | {s['commits_today']} |
| PRs open | {s['prs_open']} |
| PRs merged today | {s['prs_merged_today']} |
| PRs merged (all time) | {s['prs_merged_total']} |
| Total LOC | {s['total_loc']:,} |

## Repositories
| Source | Count |
|--------|-------|
| GitHub | {s['repos_github']} |
| Gitea | {s['repos_gitea']} |
| **Total** | **{s['repos_total']}** |

## Fleet Health
| Metric | Value |
|--------|-------|
| Nodes online | {s['fleet_online']}/{s['fleet_total']} |
| Docker containers | {s['docker_containers']} |
| Ollama models | {s['ollama_models']} |
| Avg temperature | {s['avg_temp_c']}C |
| Failed systemd units | {s['failed_units']} |
| Throttled nodes | {', '.join(s.get('throttled_nodes', [])) or 'None'} |

## Autonomy
| Metric | Value |
|--------|-------|
| Autonomy Score | **{s['autonomy_score']}/100** |

---
*Generated by [blackroad-os-kpis](https://github.com/blackboxprogramming/blackroad-os-kpis)*
'''

with open('$OUT', 'w') as f:
    f.write(md)

print(f'Report written to $OUT')
" 2>/dev/null
