name = "roadpay"
main = "src/worker.js"
compatibility_date = "2024-12-01"
workers_dev = true

routes = [
  { pattern = "pay.blackroad.io/*", zone_name = "blackroad.io" }
]

[[d1_databases]]
binding = "DB"
database_name = "tollbooth"
database_id = "29a255f5-a449-485c-90e6-38b7e4bd934d"

[[kv_namespaces]]
binding = "CACHE"
id = "68e5424a74234de197d5694127d2c3e5"

[vars]
OLLAMA_URL = "https://ollama.blackroad.io"
AUTH_API = "https://auth.blackroad.io"
