name = "analytics-blackroad"
main = "src/worker.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "analytics-blackroad"
database_id = "71e74110-3cc6-4b72-953b-569d42ed0844"
