import type { MusicTrack } from '@/lib/types'

export const MUSIC_TRACKS: MusicTrack[] = [
  {
    id: 'happy-adventure',
    name: 'Happy Adventure',
    category: 'upbeat',
    bpm: 120,
    durationSeconds: 120,
    description: 'Cheerful ukulele and claps — perfect for kids stories',
  },
  {
    id: 'morning-sunshine',
    name: 'Morning Sunshine',
    category: 'upbeat',
    bpm: 110,
    durationSeconds: 90,
    description: 'Bright piano melody with light percussion',
  },
  {
    id: 'gentle-breeze',
    name: 'Gentle Breeze',
    category: 'calm',
    bpm: 72,
    durationSeconds: 180,
    description: 'Soft acoustic guitar with nature ambiance',
  },
  {
    id: 'lullaby-dreams',
    name: 'Lullaby Dreams',
    category: 'calm',
    bpm: 60,
    durationSeconds: 150,
    description: 'Music box melody, warm pads — bedtime stories',
  },
  {
    id: 'epic-reveal',
    name: 'Epic Reveal',
    category: 'dramatic',
    bpm: 90,
    durationSeconds: 60,
    description: 'Building orchestral swell for big moments',
  },
  {
    id: 'mystery-quest',
    name: 'Mystery Quest',
    category: 'dramatic',
    bpm: 85,
    durationSeconds: 120,
    description: 'Suspenseful pizzicato strings with low brass',
  },
  {
    id: 'silly-walks',
    name: 'Silly Walks',
    category: 'playful',
    bpm: 140,
    durationSeconds: 90,
    description: 'Bouncy cartoon-style xylophone and tuba',
  },
  {
    id: 'playground-fun',
    name: 'Playground Fun',
    category: 'playful',
    bpm: 130,
    durationSeconds: 120,
    description: 'Whistling melody with hand claps and kazoo',
  },
  {
    id: 'ocean-waves',
    name: 'Ocean Waves',
    category: 'ambient',
    bpm: 0,
    durationSeconds: 300,
    description: 'Gentle ocean surf with distant seagulls',
  },
  {
    id: 'forest-morning',
    name: 'Forest Morning',
    category: 'ambient',
    bpm: 0,
    durationSeconds: 300,
    description: 'Birds chirping, rustling leaves, gentle stream',
  },
  {
    id: 'space-drift',
    name: 'Space Drift',
    category: 'ambient',
    bpm: 0,
    durationSeconds: 240,
    description: 'Deep space synth pads with ethereal textures',
  },
  {
    id: 'thinking-time',
    name: 'Thinking Time',
    category: 'calm',
    bpm: 80,
    durationSeconds: 120,
    description: 'Lo-fi piano with vinyl crackle — study/explainer videos',
  },
]

export const MUSIC_CATEGORIES = [
  { id: 'upbeat', label: 'Upbeat', icon: '🎵' },
  { id: 'calm', label: 'Calm', icon: '🌊' },
  { id: 'dramatic', label: 'Dramatic', icon: '🎭' },
  { id: 'playful', label: 'Playful', icon: '🎪' },
  { id: 'ambient', label: 'Ambient', icon: '🌿' },
] as const
