// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[projectId]" | "/[projectId]/characters" | "/[projectId]/preview" | "/[projectId]/render" | "/[projectId]/script" | "/[projectId]/share" | "/[projectId]/voice" | "/wizard"
type PageRoutes = never
type LayoutRoutes = "/" | "/[projectId]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/[projectId]": { "projectId": string; }
  "/[projectId]/characters": { "projectId": string; }
  "/[projectId]/preview": { "projectId": string; }
  "/[projectId]/render": { "projectId": string; }
  "/[projectId]/script": { "projectId": string; }
  "/[projectId]/share": { "projectId": string; }
  "/[projectId]/voice": { "projectId": string; }
  "/wizard": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[projectId]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
