// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/[projectId]/characters/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[projectId]/characters">> = Specific
  const handler = {} as typeof import("../../app/[projectId]/characters/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[projectId]">> = Specific
  const handler = {} as typeof import("../../app/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[projectId]/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[projectId]/preview">> = Specific
  const handler = {} as typeof import("../../app/[projectId]/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[projectId]/render/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[projectId]/render">> = Specific
  const handler = {} as typeof import("../../app/[projectId]/render/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[projectId]/script/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[projectId]/script">> = Specific
  const handler = {} as typeof import("../../app/[projectId]/script/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[projectId]/share/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[projectId]/share">> = Specific
  const handler = {} as typeof import("../../app/[projectId]/share/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[projectId]/voice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[projectId]/voice">> = Specific
  const handler = {} as typeof import("../../app/[projectId]/voice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/wizard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard">> = Specific
  const handler = {} as typeof import("../../app/wizard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/[projectId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[projectId]">> = Specific
  const handler = {} as typeof import("../../app/[projectId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
