name = "portal-blackroad"
main = "src/worker.js"
compatibility_date = "2024-12-01"
workers_dev = true

routes = [
  { pattern = "portal.blackroad.io/*", zone_name = "blackroad.io" }
]

[vars]
INDEX_API = "https://index-blackroad.amundsonalexa.workers.dev"
IMAGES_API = "https://images-blackroad.amundsonalexa.workers.dev"
